/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sg.com.para.intranet.common.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Project service. Represents a row in the &quot;intranet_project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link sg.com.para.intranet.common.services.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link sg.com.para.intranet.common.services.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Fernando Karnagi
 * @see Project
 * @see sg.com.para.intranet.common.services.model.impl.ProjectImpl
 * @see sg.com.para.intranet.common.services.model.impl.ProjectModelImpl
 * @generated
 */
public interface ProjectModel extends BaseModel<Project> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public int getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(int projectId);

	/**
	 * Returns the code of this project.
	 *
	 * @return the code of this project
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this project.
	 *
	 * @param code the code of this project
	 */
	public void setCode(String code);

	/**
	 * Returns the description of this project.
	 *
	 * @return the description of this project
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project.
	 *
	 * @param description the description of this project
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		sg.com.para.intranet.common.services.model.Project project);

	@Override
	public int hashCode();

	@Override
	public CacheModel<sg.com.para.intranet.common.services.model.Project> toCacheModel();

	@Override
	public sg.com.para.intranet.common.services.model.Project toEscapedModel();

	@Override
	public sg.com.para.intranet.common.services.model.Project toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}